name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/house-price-predictor:latest

  run_container:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Pull the Docker image from Docker Hub
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/house-price-predictor:latest

      # Run the Docker container
      - name: Run Docker container
        run: docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/house-price-predictor:latest
